#spring.application.name=ci
spring:
  application:
    name: ci
  datasource:
    url: jdbc:mysql://localhost:3306/devops?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create