name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: chmod
      run: chmod 744 gradlew
      # if: runner.os == 'Linux' || runner.os == 'macOS'

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      
    - name: cd
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            cd CI_SERVER
            git pull
            cd build/libs
            java -jar -Dspring.profiles.active=prod ci-0.0.1-SNAPSHOT.jar
    
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
